### ISSUE TITLE
Does it affect the efficiency of execution?

### ISSUE THREAD

**Issue by WREQI** [lo-th/hex#2]
Does it affect the efficiency of execution?

**Comment by WREQI** [comment]
I only know about draco compression and your compression. Is there any other better way to model compression?Draco and your compression method is better or two together

**Comment by lo-th** [comment]
this one is lzma compression is best than zip, draco is better but is very close and
draco modifie model so is no cool when you work for long time on optimisation of your model :)

and no you can't use both, is like compress to zip a lzma 
that give the same size
